# Generated by Django 5.2.1 on 2025-06-04 14:27

import django.db.models.deletion
import django.utils.timezone
import fleet.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permis', models.CharField(max_length=50)),
                ('numero_permis', models.CharField(max_length=50, unique=True)),
                ('date_expiration_permis', models.DateField(blank=True, null=True)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif'), ('en_conge', 'En congé')], default='actif', max_length=20)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marque', models.CharField(max_length=100)),
                ('modele', models.CharField(max_length=100)),
                ('immatriculation', models.CharField(max_length=20, unique=True)),
                ('kilometrage', models.FloatField()),
                ('assurance_expiration', models.DateField()),
                ('visite_technique', models.DateField()),
                ('carte_grise', models.FileField(blank=True, null=True, upload_to='docs/')),
                ('actif', models.BooleanField(default=True)),
                ('type_vehicule', models.CharField(choices=[('citadin', 'Citadin'), ('utilitaire', 'Utilitaire'), ('camion', 'Camion'), ('autre', 'Autre')], default='citadin', max_length=50)),
                ('capacite_reservoir', models.FloatField(default=0)),
                ('date_acquisition', models.DateField(blank=True, null=True)),
                ('prix_acquisition', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('numero_chassis', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('couleur', models.CharField(blank=True, max_length=50, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='vehicles/')),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=fleet.models.generate_code, max_length=8, unique=True)),
                ('date_depart', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_arrivee', models.DateTimeField(blank=True, null=True)),
                ('lieu_depart', models.CharField(default='', max_length=255)),
                ('lieu_arrivee', models.CharField(default='', max_length=255)),
                ('distance_km', models.FloatField(default=0)),
                ('raison', models.TextField(default='')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleet.driver')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleet.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('adresse', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('role', models.CharField(choices=[('admin', 'Administrateur'), ('gestionnaire', 'Gestionnaire'), ('conducteur', 'Conducteur')], default='conducteur', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rapport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=fleet.models.generate_code, max_length=8, unique=True)),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('type_rapport', models.CharField(choices=[('trajet', 'Trajet'), ('consommation', 'Consommation'), ('entretien', 'Entretien')], max_length=50)),
                ('date_rapport', models.DateField()),
                ('fichier', models.FileField(upload_to='rapports/')),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleet.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='driver',
            name='user_profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver', to='fleet.userprofile'),
        ),
        migrations.CreateModel(
            name='CommentaireEcart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=fleet.models.generate_code, max_length=8, unique=True)),
                ('commentaire', models.TextField()),
                ('date_commentaire', models.DateTimeField(auto_now_add=True)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleet.mission')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleet.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_entretien', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('cout', models.FloatField()),
                ('commentaire', models.TextField()),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleet.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Historique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=fleet.models.generate_code, max_length=8, unique=True)),
                ('evenement', models.CharField(choices=[('modification', 'Modification'), ('affectation', 'Affectation'), ('entretien', 'Entretien')], max_length=50)),
                ('description', models.TextField()),
                ('date_evenement', models.DateField(auto_now_add=True)),
                ('heure_evenement', models.TimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleet.userprofile')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleet.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='FuelLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('litres', models.FloatField()),
                ('cout', models.DecimalField(decimal_places=2, max_digits=10)),
                ('kilometrage', models.FloatField(default=0)),
                ('prix_litre', models.DecimalField(decimal_places=3, default=0, max_digits=5)),
                ('station', models.CharField(blank=True, max_length=100)),
                ('commentaire', models.TextField(blank=True)),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fleet.driver')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleet.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='FinancialReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('total_carburant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_entretien', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_peages', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amendes', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_autre', models.DecimalField(decimal_places=2, max_digits=10)),
                ('kilometrage_debut', models.FloatField()),
                ('kilometrage_fin', models.FloatField()),
                ('consommation_moyenne', models.FloatField()),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleet.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('carburant', 'Carburant'), ('entretien', 'Entretien'), ('assurance', 'Assurance'), ('peage', 'Péage'), ('amende', 'Amende'), ('autre', 'Autre')], max_length=20)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('justificatif', models.FileField(blank=True, null=True, upload_to='expenses/')),
                ('kilometrage', models.FloatField(blank=True, null=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleet.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Entretien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=fleet.models.generate_code, max_length=8, unique=True)),
                ('type_entretien', models.CharField(choices=[('vidange', 'Vidange'), ('pneus', 'Pneus'), ('freins', 'Freins'), ('autre', 'Autre')], max_length=50)),
                ('date_entretien', models.DateField()),
                ('cout', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commentaires', models.TextField()),
                ('kilometrage', models.FloatField()),
                ('garage', models.CharField(max_length=100)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entretiens', to='fleet.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentAdministratif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=fleet.models.generate_code, max_length=8, unique=True)),
                ('numero_document', models.CharField(max_length=50)),
                ('type_document', models.CharField(choices=[('carte_grise', 'Carte Grise'), ('assurance', 'Assurance'), ('controle_technique', 'Contrôle Technique'), ('autre', 'Autre')], max_length=50)),
                ('date_emission', models.DateField()),
                ('date_expiration', models.DateField()),
                ('fichier', models.FileField(upload_to='documents/')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='fleet.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission', models.CharField(max_length=255)),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('type_affectation', models.CharField(choices=[('temporaire', 'Temporaire'), ('permanente', 'Permanente')], max_length=50)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleet.driver')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleet.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=fleet.models.generate_code, max_length=8, unique=True)),
                ('type_alerte', models.CharField(choices=[('entretien', 'Entretien à venir'), ('assurance', 'Assurance expirée'), ('controle_technique', 'Contrôle technique'), ('autre', 'Autre')], default='autre', max_length=50)),
                ('message', models.TextField()),
                ('niveau', models.CharField(choices=[('info', 'Information'), ('warning', 'Avertissement'), ('critique', 'Critique')], default='info', max_length=20)),
                ('date_alerte', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolue', models.BooleanField(default=False)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertes', to='fleet.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Affectation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=fleet.models.generate_code, max_length=8, unique=True)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('termine', 'Terminé')], default='actif', max_length=20)),
                ('date_affectation', models.DateTimeField(auto_now_add=True)),
                ('heure_affectation', models.TimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleet.driver')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleet.vehicle')),
            ],
        ),
    ]
