# Generated by Django 5.2.1 on 2025-06-11 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertes', to='fleet.driver'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='type_alerte',
            field=models.CharField(choices=[('entretien', 'Entretien à venir'), ('assurance', 'Assurance expirée'), ('controle_technique', 'Contrôle technique'), ('permis', 'Permis de conduire'), ('autre', 'Autre')], default='autre', max_length=50),
        ),
        migrations.AlterField(
            model_name='alert',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertes', to='fleet.vehicle'),
        ),
    ]
