# Generated by Django 5.2.1 on 2025-06-13 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0002_alert_driver_alter_alert_type_alerte_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='type_vehicule',
            field=models.CharField(choices=[('SUV', 'SUV'), ('Berline', 'Berline'), ('Break', 'Break'), ('Citadine', 'Citadine'), ('4x4', '4x4'), ('Camion', 'Camion'), ('Camionnette', 'Camionnette')], default='SUV', max_length=50),
        ),
    ]
