# Generated by Django 5.2.1 on 2025-06-13 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0003_alter_vehicle_type_vehicule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='permis',
            field=models.CharField(choices=[('A', 'A - Moto'), ('B', 'B - Voiture'), ('C', 'C - Poids lourd'), ('D', 'D - Transport en commun'), ('E', 'E - Remorque'), ('F', 'F - Tracteur agricole'), ('G', 'G - Engin de chantier')], default='B', max_length=50),
        ),
    ]
