# Generated by Django 5.2.1 on 2025-06-18 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0005_vehicleposition'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='traccar_id',
            field=models.CharField(blank=True, help_text='Identifiant Traccar (ex: 960049)', max_length=32, null=True, unique=True),
        ),
    ]
