# Generated by Django 5.2.1 on 2025-06-27 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0007_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('acceptee', 'Acceptée'), ('refusee', 'Refusée'), ('en_cours', 'En cours'), ('terminee', 'Terminée'), ('planifiee', 'Planifiée')], default='en_attente', max_length=20),
        ),
    ]
