# Generated by Django 5.2.1 on 2025-07-02 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0008_mission_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='reponse_conducteur',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('acceptee', 'Acceptée'), ('refusee', 'Refusée')], default='en_attente', max_length=20),
        ),
    ]
