# Generated by Django 5.2.5 on 2025-09-18 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0009_mission_reponse_conducteur'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='type_carburant',
            field=models.CharField(blank=True, choices=[('essence', 'Essence'), ('diesel', 'Diesel'), ('electrique', 'Électrique'), ('hybride', 'Hybride'), ('autre', 'Autre')], help_text='Type de carburant du véhicule', max_length=20, null=True),
        ),
    ]
