# Generated by Django 5.2.5 on 2025-09-22 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0010_vehicle_type_carburant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='assurance_expiration',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='visite_technique',
            field=models.DateField(blank=True, null=True),
        ),
    ]
