# Generated by Django 5.2.5 on 2025-09-23 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0002_mission_coords'),
        ('fleet', '0011_alter_vehicle_assurance_expiration_and_more'),
    ]

    operations = [
    ]
