# Generated by Django 5.2.1 on 2025-06-16 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fleet', '0004_alter_driver_permis'),
    ]

    operations = [
        migrations.CreateModel(
            name='Affectation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateTimeField(verbose_name='Date de début')),
                ('date_fin', models.DateTimeField(verbose_name='Date de fin')),
                ('statut', models.CharField(choices=[('active', 'Active'), ('terminee', 'Terminée'), ('planifiee', 'Planifiée')], default='planifiee', max_length=20, verbose_name='Statut')),
                ('type_mission', models.CharField(choices=[('livraison', 'Livraison'), ('maintenance', 'Maintenance'), ('inspection', 'Inspection')], default='livraison', max_length=20, verbose_name='Type de mission')),
                ('commentaire', models.TextField(blank=True, verbose_name='Commentaire')),
                ('kilometrage_initial', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Kilométrage initial')),
                ('kilometrage_final', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Kilométrage final')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conducteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations', to='fleet.driver', verbose_name='Conducteur')),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations', to='fleet.vehicle', verbose_name='Véhicule')),
            ],
            options={
                'verbose_name': 'Affectation',
                'verbose_name_plural': 'Affectations',
                'ordering': ['-date_debut'],
            },
        ),
    ]
