# Generated by Django 5.2.1 on 2025-06-26 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affectations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affectation',
            name='kilometrage_initial',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Kilométrage initial'),
        ),
    ]
