# Generated by Django 5.2.1 on 2025-06-30 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fleet', '0008_mission_statut'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointGPS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('timestamp', models.DateTimeField()),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_gps', to='fleet.mission')),
            ],
        ),
    ]
